### ISSUE TITLE
Fix labels font size resizing

### ISSUE THREAD

**Issue by aguycalled** [navcoin/WhisperWallet#120]
Labels should get their font size reduced when the content does not fit, for example in a card.

Example:

Under “Accounts”, the title of each row overlays the right-arrow.
In the form field of the SendTo screen

- Identify other parts of the app where this can happen and apply the solution

**Comment by tsejerome** [comment]
I believe this happens usually on addresses and with places that have fix height

**Comment by tsejerome** [comment]
![image](https://user-images.githubusercontent.com/20391660/167547040-42525b0b-855d-4651-8e83-469e4af9b0ce.png)
![image](https://user-images.githubusercontent.com/20391660/167552730-a281f015-a132-4877-af04-c85bea098ba1.png)

Added a comment on Setup Staking Node, shd display the whole content on click each card instead of allowing four lines of code, but I believe its currently an edge case. Ugly but UX first.
![image](https://user-images.githubusercontent.com/20391660/167548268-071f2ff9-2bf8-4978-9144-b353c3221a94.png)
